= 函数
comyn <me@xueming.li>
v1.0
:source-highlighter: pygments
:revealjs_history: false
:revealjs_center: false
:revealjs_embedded: true
:revealjsdir: ../reveal.js
:imagesdir: assets/images/3
:homepage: http://www.magedu.com

== 什么是函数
* 函数是组织好的、可重复使用的、实现单一功能的代码段
* 函数有输入(参数)和输出(返回值)
* Python中，函数是一等对象(first class)

== 函数的定义

=== 最简单的函数定义
[source,python]
----
def fn():
    block
----

==== 调用方法
[source,python]
----
fn()
----

=== 带参数的函数定义
[source,python]
----
def fn(parameters): # <1>
    block
----
<1> 多个参数使用逗号分隔

==== 调用方法
[source,python]
----
fn(parameters)
----

=== 位置参数和关键字参数
[source,python]
----
def fn(a, b): # <1>
    pass

fn(1, 2) # <2>

fn(a=1, b=2) # <3>

fn(1, b=2) #<4>
----
<1> 函数定义
<2> 位置参数
<3> 关键字参数
<4> 混合使用， 注意：位置参数永远在关键字参数之前

=== 默认参数
[source,python]
----
def fn(a, b=2): # <1> <4>
    pass

fn(1, 3) # <2>

fn(1) # <3>
----
<1> 函数定义时，可以为参数指定一个默认值
<2> 函数调用时，可以覆盖默认值，`b=3`
<3> 也可以省略这个参数，使用默认值， `b=2`
<4> 函数定义时，带有默认值的参数应该在无默认值参数之后

=== 可变参数 -- 可变位置参数
[source,python]
----
def fn(*args): #<1>
    pass

fn(1, 2, 3) #<2>
----
<1> 函数定义时， 参数名之前加 `*` 代表此参数是可变的位置参数
<2> 函数调用时，参数列表封装成一个元组传递给 `args`

=== 思考
[source,python]
----
def f1(a, b=1, *args):
    pass

def f2(a, *args, b=1):
    pass

def f3(*args, a, b=1):
    pass
----
以上函数应该怎么调用，a, b, args的值各是什么？

=== 可变参数 -- 可变关键字参数
[source,python]
----
def fn(**kwargs): #<1> <3>
    pass

fn(a=1, b=2) # <2>
----
<1> 函数定义时，使用 `**` 表示此参数是可变的位置参数
<2> 函数调用时，关键字参数封装成字典，传递给 `kwargs`
<3> 可变关键字参数应该在参数列表的最后

=== 参数解包
[source,python]
----
a = [1, 2, 3]
b = {'a': 1, 'b': 2, 'c': 3}

def fn(a, b, c):
    pass

fn(*a) # <1>
fn(**b) # <2>
fn(*[1, 2], **{'c': 3}) # <3>
----
<1> 可以用 `*` 解包列表或者元组作为位置参数
<2> 可以用 `**` 解包字典为关键字参数
<3> 也可以混合使用，思考：`fn(*[1, 2], **{'c': 3, 'a': 4})` 会怎么样？

== 函数返回值
[%step]
* 使用 `return` 关键字返回
* 可以返回任何对象
* 可以通过解包变相返回多值
* 默认返回 `None`

== 递归函数
[%step]
* 函数体内调用自身的函数
* 递归函数需要有合适的退出条件
* 迭代都可以转化为递归
* 递归不一定可以转化为迭代
* Python递归最大深度为1000，且不支持尾递归优化
* Python中应尽量避免递归

== 作用域与全局变量
[%step]
* 作用域：变量生效的范围
* 局部变量： 在函数体内定义的变量，局部变量作用域为函数体
* 全局变量： 定义在函数体外
* 全局变量的作用域： 全局变量在任何地方都是可读的，但需要使用 `global` 关键字申明才可写
* 变量覆盖：小作用域的变量会覆盖大作用域的变量
* 全局变量可以用，但是避免写，忘记 `global` 关键字

== 文档与docstring
[source,python]
----
def fn():
    '''doc string''' # <1>
    pass
----
<1> 紧接着函数名的，使用三引号 `'''` 包围的字符串称之为docstring， `help` 函数打印的即此字符串

== 函数作为一等公民

=== 高阶函数
[source,python]
----
def add(x, y):
    return x + y

def fold(fn, *args): #<1>
    it = iter(args) #<2>
    ret = next(it)
    for x in it:
        ret = fn(ret, x)
    return ret

fold(add, 1, 2, 3, 4, 5)
----
<1> 函数作为参数传入，接收函数作为参数的函数称之为 *高阶函数*
<2> `iter` 函数分装迭代器

=== 返回函数
[source,python]
----
def external():
    def internal():
        pass
    return internal
----

== 装饰器与AOP

=== !
[source,python]
----
import time

def timeit(fn):
    def wrap(*args, **kwargs):
        start = time.time()
        fn(*args, **kwargs)
        print('call {0} spend {1}s'.format(fn.__name__, time.time() - start))
    return wrap
----


=== 使用方法
[source,python]
----
def sleep(x):
    time.sleep(x)

fn = timeit(sleep)
fn(0.2)
----

==== 更好的使用方法
[source,python]
----
@timeit # <1>
def sleep(x):
    time.sleep(x)

sleep(0.2)
----
<1> `timeit` 函数就是装饰器

=== 装饰器的本质
* 装饰器是一个函数
* 装饰器接受一个函数作为参数
* 装饰器返回一个函数，这个函数是对传入的函数封装了一些额外的操作

=== 带参数的装饰器
[source,python]
----
import time

def timeit(process_time=True):
    def _timeit(fn):
        def wrap(*args, **kwargs):
            time_fn = time.clock if process_time else time.time
            start = time_fn()
            fn(*args, **kwargs)
            print('call {0} spend {1}s'.format(fn.__name__, time_fn) - start))
        return wrap
    return _timeit
----

==== 使用方法
[source,python]
----
@timeit(False)
def sleep(x):
    time.sleep(x)
----

=== 逐步分解
* `_timeit` 函数和上一步不带参数的装饰器一样
* 所以 `timeit` 是一个函数， 这个函数返回一个装饰器
* 所以，带参数的装饰器其实是一个函数，这个函数返回一个装饰器

=== 装饰器的update
[source,python]
----
import time

def timeit(fn):
    def wrap(*args, **kwargs):
        start = time.time()
        fn(*args, **kwargs)
        #wrap.__doc__ = fn.__doc__
        #wrap.__name__ = fn.__name__
        print('call {0} spend {1}s'.format(fn.__name__, time.time() - start))
    return wrap

@timeit
def sleep(x):
    '''sleep x scond'''
    time.sleep(x)

help(sleep)
----

=== !
[source,python]
----
import time

def timeit(fn):
    def wrap(*args, **kwargs):
        start = time.time()
        fn(*args, **kwargs)
        wrap.__doc__ = fn.__doc__
        wrap.__name__ = fn.__name__
        print('call {0} spend {1}s'.format(fn.__name__, time.time() - start))
    return wrap

@timeit
def sleep(x):
    '''sleep x scond'''
    time.sleep(x)

help(sleep)
----

=== 装饰器的update
[source,python]
----
import time
import functools

def timeit(fn):
    @functools.wraps #<1>
    def wrap(*args, **kwargs):
        start = time.time()
        fn(*args, **kwargs)
        print('call {0} spend {1}s'.format(fn.__name__, time.time() - start))
    return wrap

@timeit
def sleep(x):
    '''sleep x scond'''
    time.sleep(x)

help(sleep)
----
<1> 使用 `functools.wraps` 自动update
